# Generated by Django 4.0.4 on 2022-05-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familiar2',
        ),
        migrations.DeleteModel(
            name='Familiar3',
        ),
        migrations.RenameField(
            model_name='familiar1',
            old_name='anio',
            new_name='anios',
        ),
    ]
